name = input("Enter your name : ")
age = int(input("Enter your age : "))
year = str((2014 - age) + 100)
print("Name : " + name)
print("Age : " + age)
print("You will become 100 years old in " + year)